# ===========================================
# Site Information Settings
# ===========================================

# Site creation time
since: 2018

# Custom your favicon.ico in `site/source`
favicon: /image/favicon.ico

# Set feed link (false | default | your feed link)
# false: disable
# default: use `atom.xml`, generator for `hexo-generator-feed`
rss: default

# ===========================================
# Menu Settings
# ===========================================
menu:
  Home: /
  Archives: /archives/
  Tags: /tags/
  Categories: /categories/
  About: /about/
  站内搜索: /search/

# ===========================================
# Theme Settings
# ===========================================
# theme styling
# color: Default | Mint Green | Cobalt Blue | Hot Pink | Dark Violet
theme:
  color: Default
  toc: true
  fancybox: true

copyright:
  enable: true
  # https://creativecommons.org/
  license: '<a rel="license" href="http://creativecommons.org/licenses/by-nc/4.0/" target="_blank">知识共享署名-非商业性使用 4.0 国际许可协议</a>'

reward:
  enable: true
  qrCode:
    wechat: /image/reward/wechat.jpg
    #    alipay: /image/reward/alipay.png

# ===========================================
# Social links Settings
# ===========================================
social:
  email: huangdongjie95@gmail.com
  stack-overflow:
  twitter:
  facebook:
  linkedin:
  google:
  github:
  weibo:
  zhihu:
  douban:
  pocket:
  tumblr:
  instagram:

# ===========================================
# Third Party Services Settings
# ===========================================

# LeanCloud
leancloud:
  app_id: TjF6UAmqaY3eAzBCs6z4eXns-gzGzoHsz
  app_key: vyYYDCKaSUWWkIIb77rCbCUI

# Baidu Analytics
baidu_analytics: 97be278287f06c11de869218264c132e
# Baidu Verification
baidu_verification:

# Google Analytics
google_analytics:
# Google Verification
google_verification:

# Disqus
#disqus_shortname: huangdongjiedeblog

#Changyan
changyan:
  appid:
  appkey:

#LiveRe
livere_datauid:

#Gitalk
gitalk:
  on: false
  owner: huangdongjie
  repo: blog-comment 
  admin: ['huangdongjie']
  clientID: e5ab59d5456eb882bb59
  clientSecret: 7c3b29d9b026a1293820e9f991a1731869f3167d

# ===========================================
# Version
# ===========================================
version: 2.6.0
